name: Build

on:
  push:
    branches: [ "main" ]
    paths:
        - 'src/**'
        - 'package/**'
  pull_request:
    branches: [ "main" ]

jobs:
  #Build static lua
  static-build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - uses: egor00f/install-kolibrios-toolchain-action@v1.1

    - name: install newlib
      run: sudo apt install kos-newlib

    - name: static Build
      run: cd src && make static

    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: static-build
        path: |
          ./src/lua
          ./src/luac
          ./src/liblua.a
  
  #Build shared lua
  shared-build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - uses: egor00f/install-kolibrios-toolchain-action@v1.1

    - name: install newlib
      run: sudo apt install kos-newlib

    - name: shared Build
      run: cd src && make shared

    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: shared-build
        path: |
          ./src/lua
          ./src/luac
          ./src/lua54.dll
          ./src/lua54.dll.a

  #Build syscalls library
  syscalls-lib:
    runs-on: ubuntu-latest
    needs: shared-build
    steps:
      - uses: actions/checkout@v4

      - uses: egor00f/install-kolibrios-toolchain-action@v1.1

      - name: install newlib
        run: sudo apt install kos-newlib

      - name: shared Build
        run: cd src && make syscalls.dll

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: syscalls-build
          path: ./src/syscalls.dll

  #Build package
  package-build:
    runs-on: ububntu-latest
    needs: ["shared-build", "static-build"]
    steps:
      - uses: actions/checkout@v4
      
      - uses: egor00f/install-kolibrios-toolchain-action@v1.1
    
      - name: install newlib
        run: sudo apt install kos-newlib

      - name: Build
        run: make package

      - name: Test Install
        run: sudo apt install ./package.deb

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: package-build
          path: ./package.deb
