name: Build

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  static-build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - uses: egor00f/install-kolibrios-toolchain-action@v1.1

    - name: kolibros repo
      run: cd .. && git clone https://github.com/KolibriOS/kolibrios.git

    - name: static Build
      run: cd src && make static

    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: static-build
        path: |
          ./src/lua
          ./src/luac
          ./src/liblua.a

  shared-build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - uses: egor00f/install-kolibrios-toolchain-action@v1.1

    - name: kolibros repo
      run: cd .. && git clone https://github.com/KolibriOS/kolibrios.git

    - name: shared Build
      run: cd src && make shared

    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: shared-build
        path: |
          ./src/lua
          ./src/luac
          ./src/lua54.dll
    
  syscalls-lib:
    runs-on: ubuntu-latest
    needs: shared-build
    steps:
      - uses: actions/checkout@v4

      - uses: egor00f/install-kolibrios-toolchain-action@v1.1

      - name: kolibros repo
        run: cd .. && git clone https://github.com/KolibriOS/kolibrios.git

      - name: shared Build
        run: cd src && make syscalls.dll

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: shared-build
          path: |
            ./src/syscalls.dll
