name: Makefile CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - uses: egor00f/install-kolibrios-toolchain-action@v1.1

    - name: kolibros repo
      run: cd .. && git clone https://git.kolibrios.org/KolibriOS/kolibrios.git

    - name: Build
      run: cd src && make all

    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: deb-package
        # Upload entire repository
        path: |
          ./src/lua
          ./src/luac
          ./src/liblua.a
